config/routes.rb
Rails.application.routes.draw do
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
    # rotas do site
    # scope 'site' do
        get '/' => 'site#home', as: :site_root
        get '/paginas/:slug' => 'site#page', as: :site_pages
        get '/fluxo-de-atividades' => 'site#activities', as: :site_activities
        get '/professores' => 'site#teachers', as: :site_teachers
        get '/aprovados' => 'site#approveds', as: :site_approveds
        get '/em-andamento' => 'site#in_progress', as: :site_in_progress
        get '/timeline/:tcc' => 'site#timeline', as: :site_timeline
        
        # to do
        get '/paginas' => 'site#pages', as: :site_list_pages
        get '/noticias' => 'site#notices', as: :site_notices
    # end

    # rotas gerais da aplicação
    get 'login' => 'application#login', as: :login
    post 'login' => 'application#login_post', as: :login_post
    get 'logout' => 'application#logout'
    # root 'application#login'

    # download de arquivos do dropbox
    get "files/get/:id" => "files#get", :as => "download"

    # rotas do módulo do professor responsável
    scope 'responsavel', module: 'app', as: 'responsible_teacher' do
        # dashboard
        get '/' => 'responsibleteachers/timelines#home', module: 'app'

        resources :students, module: 'responsibleteachers', path: 'academicos'
        resources :teachers, module: 'responsibleteachers', path: 'professores'

        resources :calendars, module: 'responsibleteachers', path: 'calendarios', format: :js
        get 'calendarios/:year/:half/:tcc' => 'responsibleteachers/calendars#show', module: 'app'
        get 'calendarios/:year/:half/:tcc/timeline' => 'responsibleteachers/calendars#timeline', module: 'app'
        post 'calendarios/:id/timeline/save' => 'responsibleteachers/calendars#save_timeline', module: 'app'

        resources :timelines, module: 'responsibleteachers', only: [:index, :show, :new, :create, :destroy, :edit, :update]
        get 'timelines/:year/:half/:tcc' => 'responsibleteachers/timelines#list', module: 'responsibleteachers'

        resources :banks, module: 'responsibleteachers', only: [:index, :show, :new, :create, :destroy, :edit, :update], path: 'bancas'
        resources :approvals, module: 'responsibleteachers', only: [:index, :show, :create, :destroy, :edit, :update], path: 'aprovados'
        get 'aprovados/new/:id' => 'responsibleteachers/approvals#new', as: :new_approval

        get 'orientacoes' => 'responsibleteachers/orientations#orientations'
        get 'orientacoes/:timeline' => 'responsibleteachers/orientations#orientations_by_timeline'
        get 'orientacao/:id' => 'responsibleteachers/orientations#orientation'

        resources :paginas, module: 'responsibleteachers', controller: :pages, as: :pages
        resources :noticias, module: 'responsibleteachers', controller: :notices, as: :notices
    end

    # rotas do módulo do acadêmico
    scope 'academico', module: 'app', as: 'student' do
        get '/' => 'students#timelines'
        get 'timeline/show/:id' => 'students#show_timeline', as: :show_timeline
        get 'timeline/:timeline_id/:id' => 'students#item', as: :delivery_item_get
        post 'timeline/:id' => 'students#delivery', as: :delivery_item

        get '/orientacoes' => 'students#orientations'
        get '/orientacoes/:id' => 'students#show_orientation', as: :show_orientation
        get '/orientacoes/:id/accept' => 'students#accept_orientation', as: :accept_orientation
    end

    # rotas do módulo do professor orientador / membro de banca
    scope 'professor', module: 'app', as: 'teachers' do
        get '/' => 'teachers/timelines#index'
        get 'timeline/:timeline_id/item/:id' => 'teachers/items#show', as: :item
        get 'timeline/:timeline_id/item/:id/aprovar' => 'teachers/items#approve', as: :approve
        get 'timeline/:timeline_id/item/:id/reprovar' => 'teachers/items#repprove', as: :repprove
        post 'timeline/:timeline_id/item/:id/reprovar' => 'teachers/items#repprove_post', as: :repprove_post

        get 'timelines' => 'teachers/timelines#index'
        get 'timelines/:id' => 'teachers/timelines#show', as: :timeline
        get 'timelines/:year/:half/:tcc' => 'teachers/timelines#list'

        get 'entregas' => 'teachers/items#pending', as: :pending

        get 'bancas' => 'teachers/banks#index'
        resources :orientacoes, :controller => 'orientations'
        get 'orientacoes/timeline/:timeline_id' => 'orientations#index_by_timeline'
        post 'orientacoes/:id/edit' => 'orientations#editPost'
        get 'orientacoes/:id' => 'orientations#show'
    end

    # rotas do módulo do professor de TCC 1
    scope 'tcc1', module: 'app', as: 'tcc1' do
        get '/' => 'tcc1/timelines#index'
        get 'timeline/:timeline_id/item/:id' => 'tcc1/items#show', as: :item
        get 'timeline/:timeline_id/item/:id/aprovar' => 'tcc1/items#approve', as: :approve
        get 'timeline/:timeline_id/item/:id/reprovar' => 'tcc1/items#repprove', as: :repprove
        post 'timeline/:timeline_id/item/:id/reprovar' => 'tcc1/items#repprove_post', as: :repprove_post

        get 'timelines' => 'tcc1/timelines#index'
        get 'timelines/:id' => 'tcc1/timelines#show', as: :timeline
        get 'timelines/:year/:half' => 'tcc1/timelines#list'

        get 'entregas' => 'tcc1/items#pending', as: :pending
    end

    get  'password' => 'passwords#edit'
    post 'password' => 'passwords#update', as: :edit_password
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  has_many :timelines, through: :teacher_timelines
  has_many :teacher_timelines
  has_and_belongs_to_many :banks
  has_many :bank_note
  has_many :approval
  has_one :password, :dependent => :destroy
  belongs_to :role

  validates_presence_of :name
  validates_presence_of :role_id
  validates_presence_of :email

  after_create :create_default_password

  def self.search(search)
    if search
        where(['lower(name) LIKE ?', "%#{search}%".downcase])
    else
        all
    end
  end

  private
  def create_default_password
    Password.create teacher: self, password: 'abc123'
  end
end

app/controllers/app/responsibleteacher/teachers_controller.rb
class App::Responsibleteacher::TeachersController < ApplicationController
    layout '/app/responsibleteacher'
    before_action :set_teacher, only: [:show, :edit, :update, :destroy]
    def index
        @teachers = Teacher.search(params[:search]).paginate(:page => params[:page]).order('created_at DESC')
    end

    def create
        @teacher = Teacher.new teacher_params
        if @teacher.save
            flash[:success] = t('controllers.save')
            redirect_to responsible_teacher_teachers_path
        else
            render :new
        end
    end

    def new
        @teacher = Teacher.new
    end

    def edit
    end

    def show
    end

    def update
        if @teacher.update teacher_params
            flash[:success] = t('controllers.save')
            redirect_to responsible_teacher_teachers_path
        else
            render :new
        end
    end

    def destroy
        @student.destroy
        flash[:success] = t('controllers.destroy')
        redirect_to responsible_teacher_teachers_url
    end

    private
    def teacher_params
        params.require(:teacher).permit(:name, :lattes, :atuacao, :email, :login, :role_id)
    end

    def set_teacher
        @teacher = Teacher.find(params[:id])
    end
end

app/controllers/app/responsibleteacher/timelines_controller.rb
class App::Responsibleteacher::TimelinesController < ApplicationController
  layout '/app/responsibleteacher'

  def create
    base_timeline = BaseTimeline.find_by year: params[:year], half: params[:half], tcc: params[:tcc]
    student = Student.find params[:timeline][:student]
    teachers = Array.new
    params[:timeline][:teachers].each do |teacher_id|
      teachers.push Teacher.find(teacher_id) if Teacher.exists?(teacher_id)
    end
    @timeline = Timeline.new(base_timeline: base_timeline, student: student, teachers: teachers)
    if @timeline.save
      flash[:success] = t('controllers.save')
      render :partial => 'success.js.erb'
    else
      render :partial => 'new.js.erb'
    end
  end

  def new
    @teachers = Teacher.all
    @students = Student.all
    @timeline = Timeline.new
    render :partial => 'new.js.erb'
  end

  def index
    redirect_to '/responsavel/timelines/'+Time.now.year.to_s+'/1/1'
  end

  def show
    @_calendar = Timeline.find(params[:id]).base_timeline
    @items = @_calendar.item_base_timeline
    @calendar = @_calendar.attributes
    @json = @_calendar.json
    @calendar.delete("json")
    render :partial => 'show.js.erb'
  end

  def list
    @timelines = Timeline.joins(:base_timeline).where(base_timelines: {year: params[:year], half: params[:half], tcc: params[:tcc]})
  end

  def destroy
    Timeline.find(params[:id]).destroy
    redirect_to '/responsavel/timelines'
  end
end

app/controllers/app/responsibleteachers/teachers_controller.rb
class App::Responsibleteachers::TeachersController < App::Responsibleteachers::BaseController
    layout '/app/responsibleteachers'
    before_action :set_teacher, only: [:show, :edit, :update, :destroy]
    def index
        @teachers = Teacher.search(params[:search]).paginate(:page => params[:page]).order('created_at DESC')
    end

    def create
        @teacher = Teacher.new teacher_params
        if @teacher.save
            flash[:success] = t('controllers.save')
            redirect_to responsible_teacher_teachers_path
        else
            render :new
        end
    end

    def new
        @teacher = Teacher.new
    end

    def edit
    end

    def show
    end

    def update
        if @teacher.update teacher_params
            flash[:success] = t('controllers.save')
            redirect_to responsible_teacher_teachers_path
        else
            render :new
        end
    end

    def destroy
        @student.destroy
        flash[:success] = t('controllers.destroy')
        redirect_to responsible_teacher_teachers_url
    end

    private
    def teacher_params
        params.require(:teacher).permit(:name, :lattes, :atuacao, :email, :login, :role_id, :avaliable)
    end

    def set_teacher
        @teacher = Teacher.find(params[:id])
    end
end

app/controllers/app/responsibleteachers/timelines_controller.rb
class App::Responsibleteachers::TimelinesController < App::Responsibleteachers::BaseController
  layout '/app/responsibleteachers'

  def home
    redirect_to responsible_teacher_timelines_path
  end

  def create
    base_timeline = BaseTimeline.find_by year: params[:year], half: params[:half], tcc: params[:tcc]
    student = Student.find params[:timeline][:student]
    teachers = Array.new
    params[:timeline][:teachers].each do |teacher_id|
      teachers.push Teacher.find(teacher_id) if Teacher.exists?(teacher_id)
    end
    @timeline = Timeline.new(base_timeline: base_timeline, student: student, teachers: teachers, title: params[:timeline][:title])
    if @timeline.save
      @timeline.create_items
      flash[:success] = t('controllers.save')
      render :partial => 'success.js.erb'
    else
      render :partial => 'new.js.erb'
    end
  end

  def update
    @timeline = Timeline.find(params[:id])
    teachers = Array.new
    params[:timeline][:teachers].each do |teacher_id|
      teachers.push Teacher.find(teacher_id) if Teacher.exists?(teacher_id)
    end
    if @timeline.update teachers: teachers, title: params[:timeline][:title]
      flash[:success] = t('controllers.save')
      render :partial => 'success.js.erb'
    else
      render :partial => 'new.js.erb'
    end
  end

  def new
    @timeline = Timeline.new
    render :partial => 'new.js.erb'
  end

  def edit
    @timeline = Timeline.find(params[:id])
    render :partial => 'edit.js.erb'
  end

  def index
    half = Date.today.strftime("%m").to_i < 6 ? 1 : 2
    redirect_to "/responsavel/timelines/#{Time.now.year.to_s}/#{half.to_s}/1"
  end

  def show
    timeline = Timeline.find(params[:id])
    @_calendar = timeline.base_timeline
    items = @_calendar.item_base_timeline

    @items = Array.new
    timeline.item_timelines.each do |item_timeline|
      _item = item_timeline.item_base_timeline.attributes
      _item['status'] = !item_timeline.status_item.nil? ? item_timeline.status_item.name.downcase : 'none'
      @items.push(_item)
    end

    @calendar = @_calendar.attributes
    @json = @_calendar.json
    @calendar.delete("json")
    @timeline_id = params[:id]
    
    # render :partial => 'show.js.erb'
  end

  def list
    @timelines = Timeline.joins(:base_timeline).where(base_timelines: {year: params[:year], half: params[:half], tcc: params[:tcc]})
  end

  def destroy
    Timeline.find(params[:id]).destroy
    redirect_to '/responsavel/timelines'
  end
end

app/controllers/app/tcc1/timelines_controller.rb
class App::Tcc1::TimelinesController < App::Tcc1::BaseController
  layout '/app/tcc1'
  before_filter :set_teacher
  def index
    half = Date.today.strftime("%m").to_i < 6 ? 1 : 2
    redirect_to "/tcc1/timelines/#{Time.now.year.to_s}/#{half.to_s}"
  end

  def show
    @_calendar = Timeline.find(params[:id]).base_timeline
    items = @_calendar.item_base_timeline

    @items = Array.new
    items.each do |item|
      item_timeline = ItemTimeline.find_by(timeline_id: params[:id], item_base_timeline_id: item.id)
      _item = item.attributes
      _item['status'] = item_timeline.status_item.name.downcase
      @items.push _item
    end

    @calendar = @_calendar.attributes
    @json = @_calendar.json
    @calendar.delete("json")
    @timeline_id = params[:id]
    # render :partial => 'show.js.erb'
  end

  def list
    @timelines = Timeline.joins(:base_timeline).where(base_timelines: {year: params[:year], half: params[:half], tcc: 1})
  end
end

app/controllers/app/teachers/banks_controller.rb
class App::Teachers::BanksController < App::Teachers::BaseController
  layout 'app/teachers'
  def index
    @next_banks = Bank.next_banks.joins(:banks_teachers).where(banks_teachers: {teacher_id: @teacher.id})
    @prev_banks = Bank.prev_banks.joins(:banks_teachers).where(banks_teachers: {teacher_id: @teacher.id}).paginate(:page => params[:page]).order('created_at DESC')
  end
end

app/controllers/app/teachers/base_controller.rb
class App::Teachers::BaseController < ApplicationController
  before_filter :set_teacher
  def check_permission
    if !can? :manage, :teacher
      redirect_to get_redirect_path, :flash => { :danger => t('controllers.login.forbidden') }
    end
  end
  private
  def set_teacher
    @teacher = current_user
  end
end

app/controllers/app/teachers/items_controller.rb
class App::Teachers::ItemsController < App::Teachers::BaseController
  layout 'app/teachers'
  before_filter :set_item, except: [:pending]
  before_filter :set_teacher, only: [:pending]
  after_filter :notify, only: [:approve, :repprove_post ]

  def show
  end

  def approve
    @item.status_item = StatusItem.find_by(name: "Aprovado")
    @item.note = nil
    @item.save
    flash[:success] = t('controllers.approve_item')
    redirect_to teachers_item_path(@item.timeline, @item.item_base_timeline)
  end

  def repprove
    render :note, formats: [:js]
  end

  def repprove_post
    @item.status_item = StatusItem.find_by(name: "Reprovado")
    @item.note = params[:note] if params[:note]
    @item.save
    flash[:success] = t('controllers.repprove_item')
    redirect_to teachers_item_path(@item.timeline, @item.item_base_timeline)
  end

  def pending
    timeline_ids = Timeline.joins(:teacher_timelines).where(teacher_timelines: {teacher_id: [@teacher.id]}).ids
    @items = ItemTimeline.where(status_item_id: [1,3,4], timeline_id: timeline_ids).paginate(:page => params[:page]).order('updated_at DESC')
  end

  private
  def set_item
    @timeline = Timeline.find(params[:timeline_id])
    @item_base = ItemBaseTimeline.find(params[:id])
    @item = ItemTimeline.find_by(timeline: @timeline, item_base_timeline: @item_base)
  end

  def set_teacher
    @teacher = current_user
  end

  def notify
    @item.notify
  end
end

app/controllers/app/teachers/timelines_controller.rb
class App::Teachers::TimelinesController < App::Teachers::BaseController
  layout '/app/teachers'

  def index
    half = Date.today.strftime("%m").to_i < 6 ? 1 : 2
    redirect_to "/professor/timelines/#{Time.now.year.to_s}/#{half.to_s}/1"
  end

  def show
    timeline = Timeline.find(params[:id])
    @_calendar = timeline.base_timeline
    items = @_calendar.item_base_timeline

    @items = Array.new
    timeline.item_timelines.each do |item_timeline|
      _item = item_timeline.item_base_timeline.attributes
      _item['status'] = !item_timeline.status_item.nil? ? item_timeline.status_item.name.downcase : 'none'
      @items.push(_item)
    end

    @calendar = @_calendar.attributes
    @json = @_calendar.json
    @calendar.delete("json")
    @timeline_id = params[:id]
    # render :partial => 'show.js.erb'
  end

  def list
    @timelines = Timeline.joins(:base_timeline).joins(:teacher_timelines).where(base_timelines: {year: params[:year], half: params[:half], tcc: params[:tcc]}, teacher_timelines: {teacher_id: [@teacher.id]})
  end
end

app/views/app/teachers/timelines/_header.html.erb
<%= javascript_include_tag 'app/teacher/timelines', 'data-turbolinks-track' => true %>
<br><div class="row">
    <div class="col-md-12">
        <div class="col-md-2">
            <label>Ano: </label>
            <select class="form-control" name="year">
              <% (2015..2025).each do |n| %>
                <option <%= params[:year] == n.to_s ? 'selected' : '' %>><%= n %></option>
              <% end %>
            </select>
        </div>
        <div class="col-md-2">
            <label>Semestre</label><br>
            1º <input type="radio" value="1" name="half" <%= params[:half] == '1' ? 'checked' : '' %>>
            2º <input type="radio" value="2" name="half"<%= params[:half] == '2' ? 'checked' : '' %>>
        </div>
        <div class="col-md-1">
            <label>TCC</label><br>
            1 <input type="radio" name="tcc" value="1" <%= params[:tcc] == '1' ? 'checked' : '' %>>
            2 <input type="radio" name="tcc" value="2" <%= params[:tcc] == '2' ? 'checked' : '' %>>
        </div>
        <div class="col-md-2">
          <a href="#" class="go btn btn-info">Selecionar timelines</a>
        </div>
        <div class="links col-md-3 col-md-offset-1"></div>
    </div>
</div>
<br><br>

app/views/app/teachers/timelines/_show.js.erb
$('.modal-dialog').addClass('modal-lg');
$('.modal-body').html("<%= escape_javascript(render('timeline')) %>");
$('#modal').modal('show');

app/views/app/teachers/timelines/_timeline.html.erb
<div class="labels" style="display: none;">
  <img src="/assets/timeline/icons/presentation.png" id="label-presentation">
  <img src="/assets/timeline/icons/warning.png" id="label-important">
  <img src="/assets/timeline/icons/document.svg" id="label-document">
</div>
<%= javascript_include_tag 'timeline/fabric.min', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'timeline/helpers', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'timeline/view/pattern', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'timeline/header', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'timeline/view/body', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'timeline/view/events', 'data-turbolinks-track' => true %>
<div style="overflow: scroll;">
  <canvas id="c" width="1600" height="500"></canvas>
</div>
<div class="legend">
Legenda: <div class="btn legend-btn btn-timeline-pending"></div> item pendente <div class="btn legend-btn btn-timeline-success"></div> item realizado com sucesso <div class="btn legend-btn btn-timeline-warning"></div> item deve ser entregue em breve <div class="btn legend-btn btn-timeline-repproved"></div> item reprovado <div class="btn legend-btn btn-timeline-expired"></div> data expirada
</div>
<%= javascript_tag do %>
  window.calendar = '<%= @calendar.to_json %>';
  window.json = <%= @json.to_json.html_safe %>;
  window.items = '<%= @items.to_json %>';
  set_timeline(<%= @timeline_id %>);
<% end %>

app/views/app/teachers/timelines/list.html.erb
<%= render 'header' %>
<% if @timelines.size > 0 %>
  <table class="table table-hovered">
    <th>Nome</th>
    <th>Orientador(es)</th>
    <th>Ver timeline</th>
    <% @timelines.each do |timeline| %>
    <tr>
      <td><%= timeline.student.name %></td>
      <td><%= timeline.teachers.map { |t| t.name }.join(', ') %></td>
      <td><%= link_to glyph(:list) + ' Ver',  teachers_timeline_path(timeline), class: 'btn btn-xs btn-success', "data-no-turbolink" => true %></td>
    </tr>
    <% end %>
  </table>
<% else %>
  <h3>Não há timelines a serem mostradas.</h3>
<% end %>

app/views/app/teachers/timelines/show.html.erb
<div class="labels" style="display: none;">
  <img src="/assets/timeline/icons/presentation.png" id="label-presentation">
  <img src="/assets/timeline/icons/warning.png" id="label-important">
  <img src="/assets/timeline/icons/document.svg" id="label-document">
</div>
<%= javascript_include_tag 'app/teacher/timelines', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'timeline/fabric.min', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'timeline/helpers', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'timeline/view/pattern', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'timeline/header', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'timeline/view/body', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'timeline/view/events', 'data-turbolinks-track' => true %>
<div style="overflow: scroll;">
  <canvas id="c" width="1600" height="500"></canvas>
</div>
<div class="legend">
Legenda: <div class="btn legend-btn btn-timeline-pending"></div> item pendente <div class="btn legend-btn btn-timeline-success"></div> item realizado com sucesso <div class="btn legend-btn btn-timeline-warning"></div> item deve ser entregue em breve <div class="btn legend-btn btn-timeline-repproved"></div> item reprovado <div class="btn legend-btn btn-timeline-expired"></div> data expirada
</div>
<%= javascript_tag do %>
  window.calendar = '<%= @calendar.to_json %>';
  window.json = <%= @json.to_json.html_safe %>;
  window.items = '<%= @items.to_json %>';
  set_timeline(<%= @timeline_id %>);
<% end %>