config/routes.rb
Rails.application.routes.draw do
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
    # rotas do site
    # scope 'site' do
        get '/' => 'site#home', as: :site_root
        get '/paginas/:slug' => 'site#page', as: :site_pages
        get '/fluxo-de-atividades' => 'site#activities', as: :site_activities
        get '/professores' => 'site#teachers', as: :site_teachers
        get '/aprovados' => 'site#approveds', as: :site_approveds
        get '/em-andamento' => 'site#in_progress', as: :site_in_progress
        get '/timeline/:tcc' => 'site#timeline', as: :site_timeline
        
        # to do
        get '/paginas' => 'site#pages', as: :site_list_pages
        get '/noticias' => 'site#notices', as: :site_notices
    # end

    # rotas gerais da aplicação
    get 'login' => 'application#login', as: :login
    post 'login' => 'application#login_post', as: :login_post
    get 'logout' => 'application#logout'
    # root 'application#login'

    # download de arquivos do dropbox
    get "files/get/:id" => "files#get", :as => "download"

    # rotas do módulo do professor responsável
    scope 'responsavel', module: 'app', as: 'responsible_teacher' do
        # dashboard
        get '/' => 'responsibleteachers/timelines#home', module: 'app'

        resources :students, module: 'responsibleteachers', path: 'academicos'
        resources :teachers, module: 'responsibleteachers', path: 'professores'

        resources :calendars, module: 'responsibleteachers', path: 'calendarios', format: :js
        get 'calendarios/:year/:half/:tcc' => 'responsibleteachers/calendars#show', module: 'app'
        get 'calendarios/:year/:half/:tcc/timeline' => 'responsibleteachers/calendars#timeline', module: 'app'
        post 'calendarios/:id/timeline/save' => 'responsibleteachers/calendars#save_timeline', module: 'app'

        resources :timelines, module: 'responsibleteachers', only: [:index, :show, :new, :create, :destroy, :edit, :update]
        get 'timelines/:year/:half/:tcc' => 'responsibleteachers/timelines#list', module: 'responsibleteachers'

        resources :banks, module: 'responsibleteachers', only: [:index, :show, :new, :create, :destroy, :edit, :update], path: 'bancas'
        resources :approvals, module: 'responsibleteachers', only: [:index, :show, :create, :destroy, :edit, :update], path: 'aprovados'
        get 'aprovados/new/:id' => 'responsibleteachers/approvals#new', as: :new_approval

        get 'orientacoes' => 'responsibleteachers/orientations#orientations'
        get 'orientacoes/:timeline' => 'responsibleteachers/orientations#orientations_by_timeline'
        get 'orientacao/:id' => 'responsibleteachers/orientations#orientation'

        resources :paginas, module: 'responsibleteachers', controller: :pages, as: :pages
        resources :noticias, module: 'responsibleteachers', controller: :notices, as: :notices
    end

    # rotas do módulo do acadêmico
    scope 'academico', module: 'app', as: 'student' do
        get '/' => 'students#timelines'
        get 'timeline/show/:id' => 'students#show_timeline', as: :show_timeline
        get 'timeline/:timeline_id/:id' => 'students#item', as: :delivery_item_get
        post 'timeline/:id' => 'students#delivery', as: :delivery_item

        get '/orientacoes' => 'students#orientations'
        get '/orientacoes/:id' => 'students#show_orientation', as: :show_orientation
        get '/orientacoes/:id/accept' => 'students#accept_orientation', as: :accept_orientation
    end

    # rotas do módulo do professor orientador / membro de banca
    scope 'professor', module: 'app', as: 'teachers' do
        get '/' => 'teachers/timelines#index'
        get 'timeline/:timeline_id/item/:id' => 'teachers/items#show', as: :item
        get 'timeline/:timeline_id/item/:id/aprovar' => 'teachers/items#approve', as: :approve
        get 'timeline/:timeline_id/item/:id/reprovar' => 'teachers/items#repprove', as: :repprove
        post 'timeline/:timeline_id/item/:id/reprovar' => 'teachers/items#repprove_post', as: :repprove_post

        get 'timelines' => 'teachers/timelines#index'
        get 'timelines/:id' => 'teachers/timelines#show', as: :timeline
        get 'timelines/:year/:half/:tcc' => 'teachers/timelines#list'

        get 'entregas' => 'teachers/items#pending', as: :pending

        get 'bancas' => 'teachers/banks#index'
        resources :orientacoes, :controller => 'orientations'
        get 'orientacoes/timeline/:timeline_id' => 'orientations#index_by_timeline'
        post 'orientacoes/:id/edit' => 'orientations#editPost'
        get 'orientacoes/:id' => 'orientations#show'
    end

    # rotas do módulo do professor de TCC 1
    scope 'tcc1', module: 'app', as: 'tcc1' do
        get '/' => 'tcc1/timelines#index'
        get 'timeline/:timeline_id/item/:id' => 'tcc1/items#show', as: :item
        get 'timeline/:timeline_id/item/:id/aprovar' => 'tcc1/items#approve', as: :approve
        get 'timeline/:timeline_id/item/:id/reprovar' => 'tcc1/items#repprove', as: :repprove
        post 'timeline/:timeline_id/item/:id/reprovar' => 'tcc1/items#repprove_post', as: :repprove_post

        get 'timelines' => 'tcc1/timelines#index'
        get 'timelines/:id' => 'tcc1/timelines#show', as: :timeline
        get 'timelines/:year/:half' => 'tcc1/timelines#list'

        get 'entregas' => 'tcc1/items#pending', as: :pending
    end

    get  'password' => 'passwords#edit'
    post 'password' => 'passwords#update', as: :edit_password
end

app/views/layouts/admin/_footer.html.erb
<div id="modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header" id="modal-header"></div>
        <div class="modal-body"></div>
    </div>
  </div>
</div>
<div class="col-md-12 text-center">
  <p>Para bugs, sugestões ou contato sobre o sistema, envie um e-mail para tccutfprgpuava@gmail.com.</p>
</div>
<!-- <div class="navbar navbar-inverse footer">
  <div class="col-md-12">
    <div class="right">
      UTFPR - TCC
    </div>
    <div class="left">
      Desenvolvido por Érico Dias.
    </div>
  </div>
</div> -->

app/views/layouts/admin/_header_responsible_teacher.html.erb
<div class="row header">
  <div class="col-md-12">
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <!-- para dispositivos móveis -->
      <div class="navbar-header">
        <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="#" class="navbar-brand">UTFPR - TCC</a>
      </div>
      <!-- para outros dispositivos -->
      <div id="navbarCollapse" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="<%= params[:action] == 'home' ? 'active' : '' %>"><a href="/responsavel" data-no-turbolink>Página inicial</a></li>
          <li class="<%= params[:controller] == 'app/responsibleteachers/students' ? 'active' : '' %>"><a href="/responsavel/academicos" data-no-turbolink>Acadêmicos</a></li>
          <li class="<%= params[:controller] == 'app/responsibleteachers/teachers' ? 'active' : '' %>"><a href="/responsavel/professores" data-no-turbolink>Professores</a></li>
          <li class="<%= params[:controller] == 'app/responsibleteachers/calendars' ? 'active' : '' %>"><a href="/responsavel/calendarios" data-no-turbolink>Calendários</a></li>
          <li class="<%= params[:controller] == 'app/responsibleteachers/timelines' ? 'active' : '' %>"><a href="/responsavel/timelines" data-no-turbolink>Timelines</a></li>
          <li class="<%= params[:controller] == 'app/responsibleteachers/orientations' ? 'active' : '' %>"><a href="/responsavel/orientacoes" data-no-turbolink>Orientações</a></li>
          <li class="<%= params[:controller] == 'app/responsibleteachers/banks' ? 'active' : '' %>"><a href="/responsavel/bancas" data-no-turbolink>Bancas</a></li>
          <li class="<%= params[:controller] == 'app/responsibleteachers/pages' ? 'active' : '' %>"><a href="/responsavel/paginas" data-no-turbolink>Páginas</a></li>
          <li class="<%= params[:controller] == 'app/responsibleteachers/notices' ? 'active' : '' %>"><a href="/responsavel/noticias" data-no-turbolink>Notícias</a></li>
          <!--<li><a href="#">Relatórios</a></li>-->
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="/password" data-remote="true"><span class="glyphicon glyphicon-lock"></span>Trocar senha</a></li>
          <li><a href="/logout"><span class="glyphicon glyphicon-log-out"></span>Sair</a></li>
        </ul>
      </div>
    </nav>
  </div>
</div>

app/views/layouts/admin/_header_student.html.erb
<div class="row header">
  <div class="col-md-12">
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <!-- para dispositivos móveis -->
      <div class="navbar-header">
        <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "UTFPR - TCC", student_path, class: "navbar-brand" %>
      </div>
      <!-- para outros dispositivos -->
      <div id="navbarCollapse" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="<%= params[:action] == 'timelines' ? 'active' : '' %>"><a href="/academico" data-no-turbolink>Página inicial</a></li>
          <li class="<%= params[:action] == 'orientations' ? 'active' : '' %>"><a href="/academico/orientacoes" data-no-turbolink>Orientações</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="/logout"><span class="glyphicon glyphicon-log-out"></span>Sair</a></li>
        </ul>
      </div>
    </nav>
  </div>
</div>

app/views/layouts/admin/_header_tcc1.html.erb
<div class="row header">
  <div class="col-md-12">
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <!-- para dispositivos móveis -->
      <div class="navbar-header">
        <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "UTFPR - TCC", tcc1_path, class: "navbar-brand" %>
      </div>
      <!-- para outros dispositivos -->
      <div id="navbarCollapse" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="<%= params[:controller] == 'app/tcc1/timelines' ? 'active' : '' %>"><a href="/tcc1/timelines" data-no-turbolink>Timelines</a></li>
          <li class="<%= params[:controller] == 'app/tcc1/items' ? 'active' : '' %>"><a href="/tcc1/entregas" data-no-turbolink>Entregas</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="/password" data-remote="true"><span class="glyphicon glyphicon-lock"></span>Trocar senha</a></li>
          <li><a href="/logout"><span class="glyphicon glyphicon-log-out"></span>Sair</a></li>
        </ul>
      </div>
    </nav>
  </div>
</div>

app/views/layouts/admin/_header_teacher.html.erb
<div class="row header">
  <div class="col-md-12">
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <!-- para dispositivos móveis -->
      <div class="navbar-header">
        <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "UTFPR - TCC", teachers_path, class: "navbar-brand" %>
      </div>
      <!-- para outros dispositivos -->
      <div id="navbarCollapse" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="<%= params[:controller] == 'app/teachers/timelines' ? 'active' : '' %>"><a href="/professor/timelines" data-no-turbolink>TCC's</a></li>
          <li class="<%= params[:controller] == 'app/teachers/items' && params[:action] == 'pending' ? 'active' : '' %>"><a href="/professor/entregas" data-no-turbolink>Entregas</a></li>
          <li class="<%= params[:controller] == 'app/teachers/banks' ? 'active' : '' %>"><a href="/professor/bancas" data-no-turbolink>Bancas</a></li>
          <li class="<%= params[:controller] == 'app/orientations' ? 'active' : '' %>"><a href="/professor/orientacoes" data-no-turbolink>Orientações</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="/logout"><span class="glyphicon glyphicon-log-out"></span>Sair</a></li>
        </ul>
      </div>
    </nav>
  </div>
</div>