config/routes.rb
Rails.application.routes.draw do
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
    # rotas do site
    # scope 'site' do
        get '/' => 'site#home', as: :site_root
        get '/paginas/:slug' => 'site#page', as: :site_pages
        get '/fluxo-de-atividades' => 'site#activities', as: :site_activities
        get '/professores' => 'site#teachers', as: :site_teachers
        get '/aprovados' => 'site#approveds', as: :site_approveds
        get '/em-andamento' => 'site#in_progress', as: :site_in_progress
        get '/timeline/:tcc' => 'site#timeline', as: :site_timeline
        
        # to do
        get '/paginas' => 'site#pages', as: :site_list_pages
        get '/noticias' => 'site#notices', as: :site_notices
    # end

    # rotas gerais da aplicação
    get 'login' => 'application#login', as: :login
    post 'login' => 'application#login_post', as: :login_post
    get 'logout' => 'application#logout'
    # root 'application#login'

    # download de arquivos do dropbox
    get "files/get/:id" => "files#get", :as => "download"

    # rotas do módulo do professor responsável
    scope 'responsavel', module: 'app', as: 'responsible_teacher' do
        # dashboard
        get '/' => 'responsibleteachers/timelines#home', module: 'app'

        resources :students, module: 'responsibleteachers', path: 'academicos'
        resources :teachers, module: 'responsibleteachers', path: 'professores'

        resources :calendars, module: 'responsibleteachers', path: 'calendarios', format: :js
        get 'calendarios/:year/:half/:tcc' => 'responsibleteachers/calendars#show', module: 'app'
        get 'calendarios/:year/:half/:tcc/timeline' => 'responsibleteachers/calendars#timeline', module: 'app'
        post 'calendarios/:id/timeline/save' => 'responsibleteachers/calendars#save_timeline', module: 'app'

        resources :timelines, module: 'responsibleteachers', only: [:index, :show, :new, :create, :destroy, :edit, :update]
        get 'timelines/:year/:half/:tcc' => 'responsibleteachers/timelines#list', module: 'responsibleteachers'

        resources :banks, module: 'responsibleteachers', only: [:index, :show, :new, :create, :destroy, :edit, :update], path: 'bancas'
        resources :approvals, module: 'responsibleteachers', only: [:index, :show, :create, :destroy, :edit, :update], path: 'aprovados'
        get 'aprovados/new/:id' => 'responsibleteachers/approvals#new', as: :new_approval

        get 'orientacoes' => 'responsibleteachers/orientations#orientations'
        get 'orientacoes/:timeline' => 'responsibleteachers/orientations#orientations_by_timeline'
        get 'orientacao/:id' => 'responsibleteachers/orientations#orientation'

        resources :paginas, module: 'responsibleteachers', controller: :pages, as: :pages
        resources :noticias, module: 'responsibleteachers', controller: :notices, as: :notices
    end

    # rotas do módulo do acadêmico
    scope 'academico', module: 'app', as: 'student' do
        get '/' => 'students#timelines'
        get 'timeline/show/:id' => 'students#show_timeline', as: :show_timeline
        get 'timeline/:timeline_id/:id' => 'students#item', as: :delivery_item_get
        post 'timeline/:id' => 'students#delivery', as: :delivery_item

        get '/orientacoes' => 'students#orientations'
        get '/orientacoes/:id' => 'students#show_orientation', as: :show_orientation
        get '/orientacoes/:id/accept' => 'students#accept_orientation', as: :accept_orientation
    end

    # rotas do módulo do professor orientador / membro de banca
    scope 'professor', module: 'app', as: 'teachers' do
        get '/' => 'teachers/timelines#index'
        get 'timeline/:timeline_id/item/:id' => 'teachers/items#show', as: :item
        get 'timeline/:timeline_id/item/:id/aprovar' => 'teachers/items#approve', as: :approve
        get 'timeline/:timeline_id/item/:id/reprovar' => 'teachers/items#repprove', as: :repprove
        post 'timeline/:timeline_id/item/:id/reprovar' => 'teachers/items#repprove_post', as: :repprove_post

        get 'timelines' => 'teachers/timelines#index'
        get 'timelines/:id' => 'teachers/timelines#show', as: :timeline
        get 'timelines/:year/:half/:tcc' => 'teachers/timelines#list'

        get 'entregas' => 'teachers/items#pending', as: :pending

        get 'bancas' => 'teachers/banks#index'
        resources :orientacoes, :controller => 'orientations'
        get 'orientacoes/timeline/:timeline_id' => 'orientations#index_by_timeline'
        post 'orientacoes/:id/edit' => 'orientations#editPost'
        get 'orientacoes/:id' => 'orientations#show'
    end

    # rotas do módulo do professor de TCC 1
    scope 'tcc1', module: 'app', as: 'tcc1' do
        get '/' => 'tcc1/timelines#index'
        get 'timeline/:timeline_id/item/:id' => 'tcc1/items#show', as: :item
        get 'timeline/:timeline_id/item/:id/aprovar' => 'tcc1/items#approve', as: :approve
        get 'timeline/:timeline_id/item/:id/reprovar' => 'tcc1/items#repprove', as: :repprove
        post 'timeline/:timeline_id/item/:id/reprovar' => 'tcc1/items#repprove_post', as: :repprove_post

        get 'timelines' => 'tcc1/timelines#index'
        get 'timelines/:id' => 'tcc1/timelines#show', as: :timeline
        get 'timelines/:year/:half' => 'tcc1/timelines#list'

        get 'entregas' => 'tcc1/items#pending', as: :pending
    end

    get  'password' => 'passwords#edit'
    post 'password' => 'passwords#update', as: :edit_password
end

app/controllers/site_controller.rb
class SiteController < ActionController::Base
  #caches_page :in_progress, :approveds
  before_action :set_menu_pages

  def home
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true)
    @page = Page.find_by title: "O TCC"
    @notices = Notice.order(created_at: :desc).limit(5)
    @banks = Bank.next_banks
  end
  
  def notices
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true)
    @notices = Notice.paginate(:page => params[:page], per_page: 10)
  end
  
  def page
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true, :fenced_code_blocks => true)
    @page = Page.friendly.find(params[:slug])
  end
  
  def teachers
    role = Role.find_by name: "Professor"
    @teachers = Teacher.where(role: role).paginate(:page => params[:page], per_page: 25)
  end
  
  def approveds
    #cache_page_time
    @approveds = Approval.tccs
  end
  
  def in_progress
    #cache_page_time
    @proposals = Approval.proposals
    @projects = Approval.projects
  end
  
  def activities
  end
  
  def timeline
    tcc_calendar(params[:tcc])
    @tcc_calendar = @calendar.attributes
    @tcc_json = @tcc_calendar['json']
    @tcc_calendar.delete("json")
    @tcc_items = @items
    render layout: false
  end
  
  private
  # TODO: Check if really works
  def cache_page_time
    response.headers['Cache-Control'] = 'public, max-age=300'
  end

  def tcc_calendar(tcc)
    @calendar = BaseTimeline.find_by calendar_params(tcc)
    unless @calendar
        @calendar = BaseTimeline.create calendar_params(tcc)
    end
    @items = @calendar.item_base_timeline.order(date: :asc)
  end
  
  def calendar_params(tcc)
    current_half = Date.today.month < 6 ? 1 : 2
    {year: Time.now.year, half: current_half, tcc: tcc}
  end
  
  def set_menu_pages
    exclude_ids = Page.where(title: ["O TCC", "Documentos do TCC"]).ids
    @other_pages = Page.where.not(id: exclude_ids)
  end
end

app/views/site/_approved_tcc_one.html.erb
<% approveds.keys.sort.reverse.each do |year| %>

  <article class="text-content">
  <header class="page-header">
    <h3><%= year %></h3>
  </header>	

  <% approveds[year].each do |approval| %>
    <% # TODO: todo with a better way %>
    <% next unless approval.student.final_monograph.nil? %>
    <div class="text-content">
      <ul class="tcc-approved">
        <li>
          <%= link_to approval.bank.timeline.title, approval.file.url, target: '_blank' %>
        </li>
        <li>
          <strong>Acadêmico: </strong><%= approval.bank.student.name %>
      </li>
        <li>
          <strong>Orientador (es): </strong> <%= approval.bank.advisors %>
      </li>
        <li>
          <span>Baixar:&nbsp;</span>
          <ul>
            <%= link_to_if_exists approval.file_file_name,
              type, approval, target: '_blank' %>

            <%= link_to_if_exists approval.complementary_file_file_name,
              'Arquivos complementares', approval, target: '_blank' %>
          </ul>
          </li>
        </ul>
    </div>
  <% end %>

  </article>

<% end %>

app/views/site/activities.html.erb
<% site_title 'Fluxo de Atividades' %>

<div class="row">
  <div class="col-sm-12">

    <section >
      <article class="text-content">
        <header class="page-header">
          <h2>Fluxo de Atividades do TCC</h2>
        </header>
        <p>
          O fluxo de atividades abaixo visa apresentar ao estudantes as principais
          etapas para realização do TCC no curso de Tecnologia em Sistemas para Internet.
        </p>
      </article>

      <article id="flowchart"class="">
        <%= inline_svg('tcc_tsi_fluxograma.svg') %>
      </article>

    </section>

    <section>
      <header>
        <h2>Legenda</h2>
      </header>

      <ul id="flowchart_tcc_label">
        <li class="attention"> Atividades de máxima atenção.</li>
        <li class="deliver"> Entrega de documento.</li>
        <li class="advisor"> Atividade que deve ser realizada com o orientador.</li>
        <li class="presentation"> Apresentação/Defesa </li>
        <li class="dvd"> Entrega de DVD virgem para armazenamento do TCC na biblioteca
            <a href="https://drive.google.com/file/d/0B2_vcPBwSN6CMUhDN0MyNFZFczg/view?usp=sharing" target="_blank">
            de acordo com o modelo.
          </a>
        </li>
      </ul>
    </section>

  </div>
</div>

<%= javascript_include_tag 'site/flowchart_data.js', 'data-turbolinks-track' => true %>

app/views/site/approveds.html.erb
<% site_title 'TCCs Aprovados' %>

<div class="row">

  <div class="col-sm-12">

    <header class="page-header">
      <h2>TCCs Aprovados</h2>
    </header>


    <% cache 'approveds_tccs', skip_digest: true do %>
    <% @approveds.keys.sort.reverse.each do |year| %>

      <article class="text-content">
      <header class="page-header">
        <h3><%= year %></h3>
      </header>	

      <% @approveds[year].each do |approval| %>

        <div class="text-content">
        <ul class="tcc-approved">
          <li>
            <%= link_to approval.bank.timeline.title, approval.file.url, target: '_blank' %>
          </li>
          <li>
            <strong>Acadêmico: </strong><%= approval.bank.student.name %>
        </li>
          <li>
            <strong>Orientador (es): </strong> <%= approval.bank.advisors %>
        </li>
          <li>
            <span>Baixar:&nbsp;</span>
            <ul>
              <%= link_to_if_exists approval.student.final_proposal,
                'Proposta', approval.student.final_proposal, target: '_blank' %>

              <%= link_to_if_exists approval.student.final_project,
                'Projeto', approval.student.final_project, target: '_blank' %>

              <%= link_to_if_exists approval.file_file_name,
                'Monografia', approval, target: '_blank' %>

              <%= link_to_if_exists approval.complementary_file_file_name,
                'Arquivos complementares', approval, target: '_blank' %>
            </ul>
            </li>
          </ul>
        </div>
      <% end %>

      </article>
    <% end %>
    <% end %>

   </div> 
</div>

app/views/site/home.html.erb
<% site_title 'O TCC' %>
<div class="row">

<div class="col-sm-7">

  <header class="page-header">
    <h2><%= @page.title %></h2>
  </header>

  <article class="text-content">
    <%= @markdown.render(@page.body).html_safe %>
  </article>
  
  <article class="text-content">
    <header class="page-header">
      <h2>Próximas Bancas de TCC</h2>
    </header>
    
    <table class="table table-striped fixed">
      <tr>
        <th>Data</th>
        <th>TCC</th>
        <th>Tipo</th>
      </tr>
      <% @banks.each do |bank| %>
        <tr>
          <td><%= bank.date.strftime('%d/%m/%Y %H:%M') %></td>
          <td><%= "#{bank.timeline.student.name} - #{bank.timeline.title}" %></td>
          <td><%= t('banks.'+bank._type) %></td>
        </tr>
      <% end %>
    </table>
  </article>

</div>  <!-- ./col -->

<div class="col-sm-offset-1 col-sm-4">

  <article>
    <header class="page-header">
      <h2>Últimas notícias do TCC</h2>
    </header>
  
    <% @notices.each do |notice| %>
      <div class="">
        <h4><%= notice.title %></h4>
        <p><%= @markdown.render(notice.body).html_safe %></p>
        <p class="text-muted text-right">Publicado em  <%= notice.created_at.strftime("%d/%m/%Y") %></p>
      </div>
      <hr />
    <% end %>
  </article>
  <%= link_to "Ver todas as notícias", site_notices_path %>
</div>

app/views/site/in_progress.html.erb
<% site_title 'TCCs em Andamento' %>

<div class="row">
  <div class="col-sm-12">

    <header class="page-header">
      <h2>TCCs em andamento</h2>
    </header>

    <section>
      <header class="page-header">
        <h3>Propostas de TCC</h3>
      </header>

      <% cache 'approved_proposals_tcc_one', skip_digest: true do %>
        <%= render 'site/approved_tcc_one', approveds: @proposals, type: 'Proposta' %>
      <% end %>
    </section>

    <section>

      <header class="page-header">
        <h3>Projetos de TCC</h3>
      </header>

      <% cache 'approved_projects_tcc_one', skip_digest: true do %>
        <%= render 'site/approved_tcc_one', approveds: @projects, type: 'Projeto' %>
      <% end %>
    </section>

  </div>
</div>

app/views/site/notices.html.erb
<% site_title 'Notícias' %>
<div class="row">

  <div class="col-sm-12">

    <header class="page-header">
      <h2>Notícias</h2>
    </header>
    <div class="row">
      <div class="col-md-12">
        <%= "Mostrando #{@notices.length} de #{@notices.total_entries} resultados." %>
      </div>
    </div>
      <% @notices.each do |notice| %>
        <article class="text-content">
          <div class="">
            <header class="page-header">
              <h4><%= notice.title %></h4>
            </header>
            <%= @markdown.render(notice.body).html_safe %>
            <p class="text-muted text-right">Publicado em  <%= notice.created_at.strftime("%d/%m/%Y") %></p>
          </div>
          <hr />
        </article>
      <% end %>
      
      <div class="text-center">
        <%= will_paginate @notices, :previous_label => "&laquo; Anterior", :next_label => "Próxima &raquo;", renderer: BootstrapPagination::Rails %>
      </div>

  </div> 

</div>

app/views/site/page.html.erb
<% site_title @page.title %>
<div class="row">

  <div class="col-sm-12">

    <header class="page-header">
      <h2><%= @page.title %></h2>
    </header>

    <article class="text-content">
      <%= @markdown.render(@page.body).html_safe %>
    </article>

  </div> 

</div>

app/views/site/teachers.html.erb
<% site_title 'Professores e Áreas de Pesquisa' %>
<div class="row">

  <div class="col-sm-12">

    <header class="page-header">
      <h2>Professores e Áreas de Pesquisa</h2>
    </header>

    <article class="text-content">
      <div class="clearfix">
        <div class="pull-right well well-sm">
          <%= "Mostrando #{@teachers.length} de #{@teachers.total_entries} resultados." %>
        </div>
      </div>
      
      <table class="table table-hovered">
        <tr>
          <th>Nome</th>
          <th>Atuação</th>
          <th>Lattes</th>
          <th>E-mail</th>
          <th>Disp. para orientação</th>
        </tr>
        <% @teachers.each do |teacher| %>
        <tr>
          <td><%= teacher.name %></td>
          <td><%= teacher.atuacao %></td>
          <td><%= link_to "Lattes", teacher.lattes, target: :_blank %></td>
          <td><%= teacher.email %></td>
          <td><%= teacher.avaliable? ? "Sim" : "Não" %></td>
        </tr>
        <% end %>
      </table>

      <div class="text-center">
        <%= will_paginate @teachers, :previous_label => "&laquo; Anterior", :next_label => "Próxima &raquo;", renderer: BootstrapPagination::Rails %>
      </div>
    </article>

  </div> 

</div>

app/views/site/timeline.html.erb
<div class="labels" style="display: none;">
  <img src="/assets/timeline/icons/presentation.png" id="label-presentation">
  <img src="/assets/timeline/icons/warning.png" id="label-important">
  <img src="/assets/timeline/icons/document.svg" id="label-document">
</div>
<br><br><div style="overflow: scroll;">
  <canvas id="c" width="1600" height="500"></canvas>
</div>
<%= javascript_tag do %>
  window.calendar = '<%= @tcc_calendar.to_json %>';
  window.json = <%= @tcc_json.to_json.html_safe %>;
  window.items = '<%= @tcc_items.to_json %>';
<% end %>

<%= javascript_include_tag 'timeline/fabric.min', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'timeline/helpers', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'timeline/view/pattern', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'timeline/header', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'timeline/view/body', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'site/events', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'site/calendars', 'data-turbolinks-track' => true %>